% Home screen code

home_screen = ['        Kana no Densetsu         ';...
               '                                 ';...
               '       Please choose mode        ';...
               '          1. Story Mode          ';...
               '          2. Infinite free play  ';...
               '                                 ';...
               '       Please click 1 or 2        ']

   